---
dist: bionic
language: python
python: 3.7
env:
  - CODELISTS_BASE_URL="https://codelists.codeforiati.org"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
install:
    - yarn install
    - pip install -r requirements.txt
cache:
  pip: true
  yarn: true
script:
   - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
   - secure: "EiGFAetXEDZsPGkgf2AxYmWoUsHBn9hR48VGsb2Pk9m2VxwX9JNkKdKJE7qTeoKrgOfRGinUk5LBDa2q1YuYpoB3pHB19Pf70QhNCM91B+QYhnWlvbzuY6clGkyJ+g/DES4i4bxskeYVZCg6VGvUsAibAgq4WA83dW5+gWUXWTmkAc1XL1spl4seDNsaOmlfMXpRbcpoPvGLMtwZtO0/hQAWzyNLWiKtEtigpC30oWu0v4QTvn0XQO6P9uaGwpsnuz2XIJm0vTj1eQijXp7kaB/RnQ2fPjIpcoan/UzlrEUUoXwczPHmb8BELyqZDjIuGBDDYPGXe7DvqbRhJgUUMrdsylVDzJn+n5z9kw+19LHbIAbAgKXYCr5qXRWhiY4GectCVFZwdxVwueE3jpdNMSH64w8SG2lGBvvOKHRwTfSiBEf7IWMlZr7g5shAFSAFojPoHysoPIeET10x5dFrlZpP2TuDbBteP8vWc+d5NXc4hlG9jbWOVPYcc3X+DyL3IAuIX7aotQoSwh9rM3rJsG5jlQ9PF23p6MukbQHbI1/tIHeudi8gMMwCfHjF1OmqygYAr8ZKVGzVUoZLgGRzitGSrxsm7QyapucRLOT9mtQP6LNjQYG+HPF0KHpCFNdI8G2eY8qJ+0JtpwFiF/xEqNOfYF4NxmiZWv0ZJIy14lY="
  keep_history: true
  local_dir: docs/.vuepress/dist
  target_branch: gh-pages
  on:
    branch: master
